version: '3'
services:
  app:
    volumes:
      - './:/var/www/app/'
    build: ./docker
    depends_on:
      - db
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=HostRegexp:yiigrids.sandbox.dock
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yii2_test
      MYSQL_DATABASE: yii2_test
      MYSQL_USER: yii2_test
      MYSQL_PASSWORD: yii2_test
    ports:
      - '3308:3306'
    volumes:
      - ./tmp/db:/var/lib/mysql
    networks:
      - traefik
networks:
  traefik:
    external: true
